/* 
 * Analytics
 *
 * This API will help you to manage the tracking of your clicks and your sales, get reporting on this trackings and put in place rules based on this reporting to automatically optimize your channel catalogs. \\ Also, you will be able to consult the rule execution reporting. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportByCategoryResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportByCategoryResponseLinksTests
    {
        // TODO uncomment below to declare an instance variable for ReportByCategoryResponseLinks
        //private ReportByCategoryResponseLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportByCategoryResponseLinks
            //instance = new ReportByCategoryResponseLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportByCategoryResponseLinks
        /// </summary>
        [Test]
        public void ReportByCategoryResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportByCategoryResponseLinks
            //Assert.IsInstanceOfType<ReportByCategoryResponseLinks> (instance, "variable 'instance' is a ReportByCategoryResponseLinks");
        }

        /// <summary>
        /// Test the property 'EnableAllProducts'
        /// </summary>
        [Test]
        public void EnableAllProductsTest()
        {
            // TODO unit test for the property 'EnableAllProducts'
        }
        /// <summary>
        /// Test the property 'DisableAllProducts'
        /// </summary>
        [Test]
        public void DisableAllProductsTest()
        {
            // TODO unit test for the property 'DisableAllProducts'
        }

    }

}
