/* 
 * Marketplaces - Orders
 *
 * The features exposed in this API are centered around managing Orders harvested from your configured marketplaces.\\ This includes: - fetching current information (as known by BeezUP) for a single or multiple Orders, - requesting Order harvest to synchronize your marketplaces and BeezUP accounts, - changing BeezUP data and requesting changes to your marketplaces (accepting, shipping, etc), - configuring automatic changes to marketplace based our newly fetched data, - creating and exporting reports for your Orders. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeezUPCommonLOVLink2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeezUPCommonLOVLink2Tests
    {
        // TODO uncomment below to declare an instance variable for BeezUPCommonLOVLink2
        //private BeezUPCommonLOVLink2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeezUPCommonLOVLink2
            //instance = new BeezUPCommonLOVLink2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeezUPCommonLOVLink2
        /// </summary>
        [Test]
        public void BeezUPCommonLOVLink2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeezUPCommonLOVLink2
            //Assert.IsInstanceOfType<BeezUPCommonLOVLink2> (instance, "variable 'instance' is a BeezUPCommonLOVLink2");
        }

        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Test]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'ListName'
        /// </summary>
        [Test]
        public void ListNameTest()
        {
            // TODO unit test for the property 'ListName'
        }

    }

}
