/* 
 * Channel Catalogs
 *
 * This api allows you to manage your channel catalogs.   A channel catalog is an association between your store and a channel.  You will be able to: - map your catalog colums to channel columns. - map your catalog categories to the channel categories and define a cost of this category - configure the general and cost settings of the channel - enable or disable a channel - exclude products using filters for a channel - override product values for a channel - disable or reenable a product on a channel 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing GetChannelCatalogProductInfoListRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetChannelCatalogProductInfoListRequestTests
    {
        // TODO uncomment below to declare an instance variable for GetChannelCatalogProductInfoListRequest
        //private GetChannelCatalogProductInfoListRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetChannelCatalogProductInfoListRequest
            //instance = new GetChannelCatalogProductInfoListRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetChannelCatalogProductInfoListRequest
        /// </summary>
        [Test]
        public void GetChannelCatalogProductInfoListRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetChannelCatalogProductInfoListRequest
            //Assert.IsInstanceOfType<GetChannelCatalogProductInfoListRequest> (instance, "variable 'instance' is a GetChannelCatalogProductInfoListRequest");
        }

        /// <summary>
        /// Test the property 'Sku'
        /// </summary>
        [Test]
        public void SkuTest()
        {
            // TODO unit test for the property 'Sku'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
        /// <summary>
        /// Test the property 'Overrided'
        /// </summary>
        [Test]
        public void OverridedTest()
        {
            // TODO unit test for the property 'Overrided'
        }
        /// <summary>
        /// Test the property 'Disabled'
        /// </summary>
        [Test]
        public void DisabledTest()
        {
            // TODO unit test for the property 'Disabled'
        }
        /// <summary>
        /// Test the property 'CategoryMapped'
        /// </summary>
        [Test]
        public void CategoryMappedTest()
        {
            // TODO unit test for the property 'CategoryMapped'
        }
        /// <summary>
        /// Test the property 'Excluded'
        /// </summary>
        [Test]
        public void ExcludedTest()
        {
            // TODO unit test for the property 'Excluded'
        }
        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Test]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

    }

}
