/* 
 * Marketplaces - Orders
 *
 * The features exposed in this API are centered around managing Orders harvested from your configured marketplaces.\\ This includes: - fetching current information (as known by BeezUP) for a single or multiple Orders, - requesting Order harvest to synchronize your marketplaces and BeezUP accounts, - changing BeezUP data and requesting changes to your marketplaces (accepting, shipping, etc), - configuring automatic changes to marketplace based our newly fetched data, - creating and exporting reports for your Orders. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Order
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderTests
    {
        // TODO uncomment below to declare an instance variable for Order
        //private Order instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Order
            //instance = new Order();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Order
        /// </summary>
        [Test]
        public void OrderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Order
            //Assert.IsInstanceOfType<Order> (instance, "variable 'instance' is a Order");
        }

        /// <summary>
        /// Test the property 'MarketplaceTechnicalCode'
        /// </summary>
        [Test]
        public void MarketplaceTechnicalCodeTest()
        {
            // TODO unit test for the property 'MarketplaceTechnicalCode'
        }
        /// <summary>
        /// Test the property 'AccountId'
        /// </summary>
        [Test]
        public void AccountIdTest()
        {
            // TODO unit test for the property 'AccountId'
        }
        /// <summary>
        /// Test the property 'BeezUPOrderId'
        /// </summary>
        [Test]
        public void BeezUPOrderIdTest()
        {
            // TODO unit test for the property 'BeezUPOrderId'
        }
        /// <summary>
        /// Test the property 'BeezUPOrderUrl'
        /// </summary>
        [Test]
        public void BeezUPOrderUrlTest()
        {
            // TODO unit test for the property 'BeezUPOrderUrl'
        }
        /// <summary>
        /// Test the property 'MarketplaceBusinessCode'
        /// </summary>
        [Test]
        public void MarketplaceBusinessCodeTest()
        {
            // TODO unit test for the property 'MarketplaceBusinessCode'
        }
        /// <summary>
        /// Test the property 'OrderMarketplaceOrderId'
        /// </summary>
        [Test]
        public void OrderMarketplaceOrderIdTest()
        {
            // TODO unit test for the property 'OrderMarketplaceOrderId'
        }
        /// <summary>
        /// Test the property 'OrderStatusBeezUPOrderStatus'
        /// </summary>
        [Test]
        public void OrderStatusBeezUPOrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatusBeezUPOrderStatus'
        }
        /// <summary>
        /// Test the property 'OrderStatusMarketplaceOrderStatus'
        /// </summary>
        [Test]
        public void OrderStatusMarketplaceOrderStatusTest()
        {
            // TODO unit test for the property 'OrderStatusMarketplaceOrderStatus'
        }
        /// <summary>
        /// Test the property 'OrderMerchantOrderId'
        /// </summary>
        [Test]
        public void OrderMerchantOrderIdTest()
        {
            // TODO unit test for the property 'OrderMerchantOrderId'
        }
        /// <summary>
        /// Test the property 'OrderMerchantECommerceSoftwareName'
        /// </summary>
        [Test]
        public void OrderMerchantECommerceSoftwareNameTest()
        {
            // TODO unit test for the property 'OrderMerchantECommerceSoftwareName'
        }
        /// <summary>
        /// Test the property 'OrderMerchantECommerceSoftwareVersion'
        /// </summary>
        [Test]
        public void OrderMerchantECommerceSoftwareVersionTest()
        {
            // TODO unit test for the property 'OrderMerchantECommerceSoftwareVersion'
        }
        /// <summary>
        /// Test the property 'OrderPurchaseUtcDate'
        /// </summary>
        [Test]
        public void OrderPurchaseUtcDateTest()
        {
            // TODO unit test for the property 'OrderPurchaseUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderLastModificationUtcDate'
        /// </summary>
        [Test]
        public void OrderLastModificationUtcDateTest()
        {
            // TODO unit test for the property 'OrderLastModificationUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderMarketplaceLastModificationUtcDate'
        /// </summary>
        [Test]
        public void OrderMarketplaceLastModificationUtcDateTest()
        {
            // TODO unit test for the property 'OrderMarketplaceLastModificationUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderBuyerName'
        /// </summary>
        [Test]
        public void OrderBuyerNameTest()
        {
            // TODO unit test for the property 'OrderBuyerName'
        }
        /// <summary>
        /// Test the property 'OrderTotalPrice'
        /// </summary>
        [Test]
        public void OrderTotalPriceTest()
        {
            // TODO unit test for the property 'OrderTotalPrice'
        }
        /// <summary>
        /// Test the property 'OrderCurrencyCode'
        /// </summary>
        [Test]
        public void OrderCurrencyCodeTest()
        {
            // TODO unit test for the property 'OrderCurrencyCode'
        }
        /// <summary>
        /// Test the property 'Processing'
        /// </summary>
        [Test]
        public void ProcessingTest()
        {
            // TODO unit test for the property 'Processing'
        }
        /// <summary>
        /// Test the property 'Etag'
        /// </summary>
        [Test]
        public void EtagTest()
        {
            // TODO unit test for the property 'Etag'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }
        /// <summary>
        /// Test the property 'OrderMarketPlaceChannel'
        /// </summary>
        [Test]
        public void OrderMarketPlaceChannelTest()
        {
            // TODO unit test for the property 'OrderMarketPlaceChannel'
        }
        /// <summary>
        /// Test the property 'OrderTotalTax'
        /// </summary>
        [Test]
        public void OrderTotalTaxTest()
        {
            // TODO unit test for the property 'OrderTotalTax'
        }
        /// <summary>
        /// Test the property 'OrderTotalCommission'
        /// </summary>
        [Test]
        public void OrderTotalCommissionTest()
        {
            // TODO unit test for the property 'OrderTotalCommission'
        }
        /// <summary>
        /// Test the property 'OrderPaymentMethod'
        /// </summary>
        [Test]
        public void OrderPaymentMethodTest()
        {
            // TODO unit test for the property 'OrderPaymentMethod'
        }
        /// <summary>
        /// Test the property 'OrderPayingUtcDate'
        /// </summary>
        [Test]
        public void OrderPayingUtcDateTest()
        {
            // TODO unit test for the property 'OrderPayingUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderComment'
        /// </summary>
        [Test]
        public void OrderCommentTest()
        {
            // TODO unit test for the property 'OrderComment'
        }
        /// <summary>
        /// Test the property 'OrderShippingCivility'
        /// </summary>
        [Test]
        public void OrderShippingCivilityTest()
        {
            // TODO unit test for the property 'OrderShippingCivility'
        }
        /// <summary>
        /// Test the property 'OrderShippingCompanyName'
        /// </summary>
        [Test]
        public void OrderShippingCompanyNameTest()
        {
            // TODO unit test for the property 'OrderShippingCompanyName'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressName'
        /// </summary>
        [Test]
        public void OrderShippingAddressNameTest()
        {
            // TODO unit test for the property 'OrderShippingAddressName'
        }
        /// <summary>
        /// Test the property 'OrderShippingEmail'
        /// </summary>
        [Test]
        public void OrderShippingEmailTest()
        {
            // TODO unit test for the property 'OrderShippingEmail'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressLine1'
        /// </summary>
        [Test]
        public void OrderShippingAddressLine1Test()
        {
            // TODO unit test for the property 'OrderShippingAddressLine1'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressLine2'
        /// </summary>
        [Test]
        public void OrderShippingAddressLine2Test()
        {
            // TODO unit test for the property 'OrderShippingAddressLine2'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressLine3'
        /// </summary>
        [Test]
        public void OrderShippingAddressLine3Test()
        {
            // TODO unit test for the property 'OrderShippingAddressLine3'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressPostalCode'
        /// </summary>
        [Test]
        public void OrderShippingAddressPostalCodeTest()
        {
            // TODO unit test for the property 'OrderShippingAddressPostalCode'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressCity'
        /// </summary>
        [Test]
        public void OrderShippingAddressCityTest()
        {
            // TODO unit test for the property 'OrderShippingAddressCity'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressStateOrRegion'
        /// </summary>
        [Test]
        public void OrderShippingAddressStateOrRegionTest()
        {
            // TODO unit test for the property 'OrderShippingAddressStateOrRegion'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressCountryName'
        /// </summary>
        [Test]
        public void OrderShippingAddressCountryNameTest()
        {
            // TODO unit test for the property 'OrderShippingAddressCountryName'
        }
        /// <summary>
        /// Test the property 'OrderShippingAddressCountryIsoCodeAlpha2'
        /// </summary>
        [Test]
        public void OrderShippingAddressCountryIsoCodeAlpha2Test()
        {
            // TODO unit test for the property 'OrderShippingAddressCountryIsoCodeAlpha2'
        }
        /// <summary>
        /// Test the property 'OrderShippingPhone'
        /// </summary>
        [Test]
        public void OrderShippingPhoneTest()
        {
            // TODO unit test for the property 'OrderShippingPhone'
        }
        /// <summary>
        /// Test the property 'OrderShippingMobilePhone'
        /// </summary>
        [Test]
        public void OrderShippingMobilePhoneTest()
        {
            // TODO unit test for the property 'OrderShippingMobilePhone'
        }
        /// <summary>
        /// Test the property 'OrderShippingPrice'
        /// </summary>
        [Test]
        public void OrderShippingPriceTest()
        {
            // TODO unit test for the property 'OrderShippingPrice'
        }
        /// <summary>
        /// Test the property 'OrderShippingMethod'
        /// </summary>
        [Test]
        public void OrderShippingMethodTest()
        {
            // TODO unit test for the property 'OrderShippingMethod'
        }
        /// <summary>
        /// Test the property 'OrderShippingShippingTax'
        /// </summary>
        [Test]
        public void OrderShippingShippingTaxTest()
        {
            // TODO unit test for the property 'OrderShippingShippingTax'
        }
        /// <summary>
        /// Test the property 'OrderShippingEarliestShipUtcDate'
        /// </summary>
        [Test]
        public void OrderShippingEarliestShipUtcDateTest()
        {
            // TODO unit test for the property 'OrderShippingEarliestShipUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderShippingLatestShipUtcDate'
        /// </summary>
        [Test]
        public void OrderShippingLatestShipUtcDateTest()
        {
            // TODO unit test for the property 'OrderShippingLatestShipUtcDate'
        }
        /// <summary>
        /// Test the property 'OrderBuyerIdentifier'
        /// </summary>
        [Test]
        public void OrderBuyerIdentifierTest()
        {
            // TODO unit test for the property 'OrderBuyerIdentifier'
        }
        /// <summary>
        /// Test the property 'OrderBuyerCivility'
        /// </summary>
        [Test]
        public void OrderBuyerCivilityTest()
        {
            // TODO unit test for the property 'OrderBuyerCivility'
        }
        /// <summary>
        /// Test the property 'OrderBuyerCompanyName'
        /// </summary>
        [Test]
        public void OrderBuyerCompanyNameTest()
        {
            // TODO unit test for the property 'OrderBuyerCompanyName'
        }
        /// <summary>
        /// Test the property 'OrderBuyerEmail'
        /// </summary>
        [Test]
        public void OrderBuyerEmailTest()
        {
            // TODO unit test for the property 'OrderBuyerEmail'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressLine1'
        /// </summary>
        [Test]
        public void OrderBuyerAddressLine1Test()
        {
            // TODO unit test for the property 'OrderBuyerAddressLine1'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressLine2'
        /// </summary>
        [Test]
        public void OrderBuyerAddressLine2Test()
        {
            // TODO unit test for the property 'OrderBuyerAddressLine2'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressLine3'
        /// </summary>
        [Test]
        public void OrderBuyerAddressLine3Test()
        {
            // TODO unit test for the property 'OrderBuyerAddressLine3'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressPostalCode'
        /// </summary>
        [Test]
        public void OrderBuyerAddressPostalCodeTest()
        {
            // TODO unit test for the property 'OrderBuyerAddressPostalCode'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressCity'
        /// </summary>
        [Test]
        public void OrderBuyerAddressCityTest()
        {
            // TODO unit test for the property 'OrderBuyerAddressCity'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressStateOrRegion'
        /// </summary>
        [Test]
        public void OrderBuyerAddressStateOrRegionTest()
        {
            // TODO unit test for the property 'OrderBuyerAddressStateOrRegion'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressCountryName'
        /// </summary>
        [Test]
        public void OrderBuyerAddressCountryNameTest()
        {
            // TODO unit test for the property 'OrderBuyerAddressCountryName'
        }
        /// <summary>
        /// Test the property 'OrderBuyerAddressCountryIsoCodeAlpha2'
        /// </summary>
        [Test]
        public void OrderBuyerAddressCountryIsoCodeAlpha2Test()
        {
            // TODO unit test for the property 'OrderBuyerAddressCountryIsoCodeAlpha2'
        }
        /// <summary>
        /// Test the property 'OrderBuyerPhone'
        /// </summary>
        [Test]
        public void OrderBuyerPhoneTest()
        {
            // TODO unit test for the property 'OrderBuyerPhone'
        }
        /// <summary>
        /// Test the property 'OrderBuyerMobilePhone'
        /// </summary>
        [Test]
        public void OrderBuyerMobilePhoneTest()
        {
            // TODO unit test for the property 'OrderBuyerMobilePhone'
        }
        /// <summary>
        /// Test the property 'OrderOrderSourceUri'
        /// </summary>
        [Test]
        public void OrderOrderSourceUriTest()
        {
            // TODO unit test for the property 'OrderOrderSourceUri'
        }
        /// <summary>
        /// Test the property 'OrderOrderItemsSourceUri'
        /// </summary>
        [Test]
        public void OrderOrderItemsSourceUriTest()
        {
            // TODO unit test for the property 'OrderOrderItemsSourceUri'
        }
        /// <summary>
        /// Test the property 'OrderItems'
        /// </summary>
        [Test]
        public void OrderItemsTest()
        {
            // TODO unit test for the property 'OrderItems'
        }
        /// <summary>
        /// Test the property 'TransitionLinks'
        /// </summary>
        [Test]
        public void TransitionLinksTest()
        {
            // TODO unit test for the property 'TransitionLinks'
        }

    }

}
