/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeezUPCommonProductBasicInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeezUPCommonProductBasicInfoTests
    {
        // TODO uncomment below to declare an instance variable for BeezUPCommonProductBasicInfo
        //private BeezUPCommonProductBasicInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeezUPCommonProductBasicInfo
            //instance = new BeezUPCommonProductBasicInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeezUPCommonProductBasicInfo
        /// </summary>
        [Test]
        public void BeezUPCommonProductBasicInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeezUPCommonProductBasicInfo
            //Assert.IsInstanceOfType<BeezUPCommonProductBasicInfo> (instance, "variable 'instance' is a BeezUPCommonProductBasicInfo");
        }

        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Test]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'ProductSku'
        /// </summary>
        [Test]
        public void ProductSkuTest()
        {
            // TODO unit test for the property 'ProductSku'
        }
        /// <summary>
        /// Test the property 'ProductTitle'
        /// </summary>
        [Test]
        public void ProductTitleTest()
        {
            // TODO unit test for the property 'ProductTitle'
        }
        /// <summary>
        /// Test the property 'ProductImageUrl'
        /// </summary>
        [Test]
        public void ProductImageUrlTest()
        {
            // TODO unit test for the property 'ProductImageUrl'
        }
        /// <summary>
        /// Test the property 'ProductActive'
        /// </summary>
        [Test]
        public void ProductActiveTest()
        {
            // TODO unit test for the property 'ProductActive'
        }

    }

}
