/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OfferContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OfferContentTests
    {
        // TODO uncomment below to declare an instance variable for OfferContent
        //private OfferContent instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OfferContent
            //instance = new OfferContent();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OfferContent
        /// </summary>
        [Test]
        public void OfferContentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OfferContent
            //Assert.IsInstanceOfType<OfferContent> (instance, "variable 'instance' is a OfferContent");
        }

        /// <summary>
        /// Test the property 'PreviousFixPeriodInvoiceProrataInfo'
        /// </summary>
        [Test]
        public void PreviousFixPeriodInvoiceProrataInfoTest()
        {
            // TODO unit test for the property 'PreviousFixPeriodInvoiceProrataInfo'
        }
        /// <summary>
        /// Test the property 'ContractBillingPeriodInfo'
        /// </summary>
        [Test]
        public void ContractBillingPeriodInfoTest()
        {
            // TODO unit test for the property 'ContractBillingPeriodInfo'
        }
        /// <summary>
        /// Test the property 'ContractClickInfo'
        /// </summary>
        [Test]
        public void ContractClickInfoTest()
        {
            // TODO unit test for the property 'ContractClickInfo'
        }
        /// <summary>
        /// Test the property 'ContractCommitmentInfo'
        /// </summary>
        [Test]
        public void ContractCommitmentInfoTest()
        {
            // TODO unit test for the property 'ContractCommitmentInfo'
        }
        /// <summary>
        /// Test the property 'ContractDiscountInfo'
        /// </summary>
        [Test]
        public void ContractDiscountInfoTest()
        {
            // TODO unit test for the property 'ContractDiscountInfo'
        }
        /// <summary>
        /// Test the property 'ContractMoneyInfo'
        /// </summary>
        [Test]
        public void ContractMoneyInfoTest()
        {
            // TODO unit test for the property 'ContractMoneyInfo'
        }
        /// <summary>
        /// Test the property 'ContractStoreInfo'
        /// </summary>
        [Test]
        public void ContractStoreInfoTest()
        {
            // TODO unit test for the property 'ContractStoreInfo'
        }
        /// <summary>
        /// Test the property 'ContractBonusInfo'
        /// </summary>
        [Test]
        public void ContractBonusInfoTest()
        {
            // TODO unit test for the property 'ContractBonusInfo'
        }
        /// <summary>
        /// Test the property 'ContractTerminationReasonType'
        /// </summary>
        [Test]
        public void ContractTerminationReasonTypeTest()
        {
            // TODO unit test for the property 'ContractTerminationReasonType'
        }
        /// <summary>
        /// Test the property 'ContractTerminationReason'
        /// </summary>
        [Test]
        public void ContractTerminationReasonTest()
        {
            // TODO unit test for the property 'ContractTerminationReason'
        }
        /// <summary>
        /// Test the property 'NotifyVatExemption'
        /// </summary>
        [Test]
        public void NotifyVatExemptionTest()
        {
            // TODO unit test for the property 'NotifyVatExemption'
        }

    }

}
