/* 
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BillingPeriod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BillingPeriodTests
    {
        // TODO uncomment below to declare an instance variable for BillingPeriod
        //private BillingPeriod instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BillingPeriod
            //instance = new BillingPeriod();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BillingPeriod
        /// </summary>
        [Test]
        public void BillingPeriodInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BillingPeriod
            //Assert.IsInstanceOfType<BillingPeriod> (instance, "variable 'instance' is a BillingPeriod");
        }

        /// <summary>
        /// Test the property 'BillingPeriodInMonth'
        /// </summary>
        [Test]
        public void BillingPeriodInMonthTest()
        {
            // TODO unit test for the property 'BillingPeriodInMonth'
        }
        /// <summary>
        /// Test the property 'DiscountPercentage'
        /// </summary>
        [Test]
        public void DiscountPercentageTest()
        {
            // TODO unit test for the property 'DiscountPercentage'
        }

    }

}
