/* 
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoreSharesLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreSharesLinksTests
    {
        // TODO uncomment below to declare an instance variable for StoreSharesLinks
        //private StoreSharesLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreSharesLinks
            //instance = new StoreSharesLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreSharesLinks
        /// </summary>
        [Test]
        public void StoreSharesLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreSharesLinks
            //Assert.IsInstanceOfType<StoreSharesLinks> (instance, "variable 'instance' is a StoreSharesLinks");
        }

        /// <summary>
        /// Test the property 'Share'
        /// </summary>
        [Test]
        public void ShareTest()
        {
            // TODO unit test for the property 'Share'
        }

    }

}
