/* 
 * BeezUP API
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ChannelCatalogMarketplaceProperties
    /// </summary>
    [DataContract]
    public partial class ChannelCatalogMarketplaceProperties :  IEquatable<ChannelCatalogMarketplaceProperties>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelCatalogMarketplaceProperties" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ChannelCatalogMarketplaceProperties() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelCatalogMarketplaceProperties" /> class.
        /// </summary>
        /// <param name="Info">Info.</param>
        /// <param name="Links">Links (required).</param>
        /// <param name="PropertyGroups">The groups settings with constraints (required).</param>
        public ChannelCatalogMarketplaceProperties(BeezUPCommonInfoSummaries Info = default(BeezUPCommonInfoSummaries), ChannelCatalogMarketplacePropertiesLinks Links = default(ChannelCatalogMarketplacePropertiesLinks), List<ChannelCatalogMarketplacePropertyGroup> PropertyGroups = default(List<ChannelCatalogMarketplacePropertyGroup>))
        {
            // to ensure "Links" is required (not null)
            if (Links == null)
            {
                throw new InvalidDataException("Links is a required property for ChannelCatalogMarketplaceProperties and cannot be null");
            }
            else
            {
                this.Links = Links;
            }
            // to ensure "PropertyGroups" is required (not null)
            if (PropertyGroups == null)
            {
                throw new InvalidDataException("PropertyGroups is a required property for ChannelCatalogMarketplaceProperties and cannot be null");
            }
            else
            {
                this.PropertyGroups = PropertyGroups;
            }
            this.Info = Info;
        }
        
        /// <summary>
        /// Gets or Sets Info
        /// </summary>
        [DataMember(Name="info", EmitDefaultValue=false)]
        public BeezUPCommonInfoSummaries Info { get; set; }
        /// <summary>
        /// Gets or Sets Links
        /// </summary>
        [DataMember(Name="links", EmitDefaultValue=false)]
        public ChannelCatalogMarketplacePropertiesLinks Links { get; set; }
        /// <summary>
        /// The groups settings with constraints
        /// </summary>
        /// <value>The groups settings with constraints</value>
        [DataMember(Name="propertyGroups", EmitDefaultValue=false)]
        public List<ChannelCatalogMarketplacePropertyGroup> PropertyGroups { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ChannelCatalogMarketplaceProperties {\n");
            sb.Append("  Info: ").Append(Info).Append("\n");
            sb.Append("  Links: ").Append(Links).Append("\n");
            sb.Append("  PropertyGroups: ").Append(PropertyGroups).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as ChannelCatalogMarketplaceProperties);
        }

        /// <summary>
        /// Returns true if ChannelCatalogMarketplaceProperties instances are equal
        /// </summary>
        /// <param name="other">Instance of ChannelCatalogMarketplaceProperties to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ChannelCatalogMarketplaceProperties other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.Info == other.Info ||
                    this.Info != null &&
                    this.Info.Equals(other.Info)
                ) && 
                (
                    this.Links == other.Links ||
                    this.Links != null &&
                    this.Links.Equals(other.Links)
                ) && 
                (
                    this.PropertyGroups == other.PropertyGroups ||
                    this.PropertyGroups != null &&
                    this.PropertyGroups.SequenceEqual(other.PropertyGroups)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.Info != null)
                    hash = hash * 59 + this.Info.GetHashCode();
                if (this.Links != null)
                    hash = hash * 59 + this.Links.GetHashCode();
                if (this.PropertyGroups != null)
                    hash = hash * 59 + this.PropertyGroups.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
