/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Invoices
    /// </summary>
    [DataContract]
    public partial class Invoices :  IEquatable<Invoices>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Invoices" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected Invoices() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="Invoices" /> class.
        /// </summary>
        /// <param name="_Invoices">_Invoices (required).</param>
        public Invoices(List<Invoice> _Invoices = default(List<Invoice>))
        {
            // to ensure "_Invoices" is required (not null)
            if (_Invoices == null)
            {
                throw new InvalidDataException("_Invoices is a required property for Invoices and cannot be null");
            }
            else
            {
                this._Invoices = _Invoices;
            }
        }
        
        /// <summary>
        /// Gets or Sets _Invoices
        /// </summary>
        [DataMember(Name="invoices", EmitDefaultValue=false)]
        public List<Invoice> _Invoices { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Invoices {\n");
            sb.Append("  _Invoices: ").Append(_Invoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as Invoices);
        }

        /// <summary>
        /// Returns true if Invoices instances are equal
        /// </summary>
        /// <param name="other">Instance of Invoices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Invoices other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._Invoices == other._Invoices ||
                    this._Invoices != null &&
                    this._Invoices.SequenceEqual(other._Invoices)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._Invoices != null)
                    hash = hash * 59 + this._Invoices.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
