/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChannelHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChannelHeaderTests
    {
        // TODO uncomment below to declare an instance variable for ChannelHeader
        //private ChannelHeader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChannelHeader
            //instance = new ChannelHeader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChannelHeader
        /// </summary>
        [Test]
        public void ChannelHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChannelHeader
            //Assert.IsInstanceOfType<ChannelHeader> (instance, "variable 'instance' is a ChannelHeader");
        }

        /// <summary>
        /// Test the property 'ChannelId'
        /// </summary>
        [Test]
        public void ChannelIdTest()
        {
            // TODO unit test for the property 'ChannelId'
        }
        /// <summary>
        /// Test the property 'ChannelName'
        /// </summary>
        [Test]
        public void ChannelNameTest()
        {
            // TODO unit test for the property 'ChannelName'
        }
        /// <summary>
        /// Test the property 'ChannelLogoUrl'
        /// </summary>
        [Test]
        public void ChannelLogoUrlTest()
        {
            // TODO unit test for the property 'ChannelLogoUrl'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
