/* 
 * Public - Security
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChangeCustomColumnExpressionRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChangeCustomColumnExpressionRequestTests
    {
        // TODO uncomment below to declare an instance variable for ChangeCustomColumnExpressionRequest
        //private ChangeCustomColumnExpressionRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChangeCustomColumnExpressionRequest
            //instance = new ChangeCustomColumnExpressionRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChangeCustomColumnExpressionRequest
        /// </summary>
        [Test]
        public void ChangeCustomColumnExpressionRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChangeCustomColumnExpressionRequest
            //Assert.IsInstanceOfType<ChangeCustomColumnExpressionRequest> (instance, "variable 'instance' is a ChangeCustomColumnExpressionRequest");
        }

        /// <summary>
        /// Test the property 'EncryptedExpression'
        /// </summary>
        [Test]
        public void EncryptedExpressionTest()
        {
            // TODO unit test for the property 'EncryptedExpression'
        }
        /// <summary>
        /// Test the property 'EncryptedBlocklyExpression'
        /// </summary>
        [Test]
        public void EncryptedBlocklyExpressionTest()
        {
            // TODO unit test for the property 'EncryptedBlocklyExpression'
        }

    }

}
