/* 
 * Public - Security
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChannelCatalogMarketplacePropertiesLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChannelCatalogMarketplacePropertiesLinksTests
    {
        // TODO uncomment below to declare an instance variable for ChannelCatalogMarketplacePropertiesLinks
        //private ChannelCatalogMarketplacePropertiesLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChannelCatalogMarketplacePropertiesLinks
            //instance = new ChannelCatalogMarketplacePropertiesLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChannelCatalogMarketplacePropertiesLinks
        /// </summary>
        [Test]
        public void ChannelCatalogMarketplacePropertiesLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChannelCatalogMarketplacePropertiesLinks
            //Assert.IsInstanceOfType<ChannelCatalogMarketplacePropertiesLinks> (instance, "variable 'instance' is a ChannelCatalogMarketplacePropertiesLinks");
        }

        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'Settings'
        /// </summary>
        [Test]
        public void SettingsTest()
        {
            // TODO unit test for the property 'Settings'
        }

    }

}
