/* 
 * BeezUP API
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ChannelCatalogCategoryMappingInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ChannelCatalogCategoryMappingInfoTests
    {
        // TODO uncomment below to declare an instance variable for ChannelCatalogCategoryMappingInfo
        //private ChannelCatalogCategoryMappingInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ChannelCatalogCategoryMappingInfo
            //instance = new ChannelCatalogCategoryMappingInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ChannelCatalogCategoryMappingInfo
        /// </summary>
        [Test]
        public void ChannelCatalogCategoryMappingInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ChannelCatalogCategoryMappingInfo
            //Assert.IsInstanceOfType<ChannelCatalogCategoryMappingInfo> (instance, "variable 'instance' is a ChannelCatalogCategoryMappingInfo");
        }

        /// <summary>
        /// Test the property 'CatalogCategoryPath'
        /// </summary>
        [Test]
        public void CatalogCategoryPathTest()
        {
            // TODO unit test for the property 'CatalogCategoryPath'
        }
        /// <summary>
        /// Test the property 'ChannelCategoryPath'
        /// </summary>
        [Test]
        public void ChannelCategoryPathTest()
        {
            // TODO unit test for the property 'ChannelCategoryPath'
        }
        /// <summary>
        /// Test the property 'CostValue'
        /// </summary>
        [Test]
        public void CostValueTest()
        {
            // TODO unit test for the property 'CostValue'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
