/* 
 * BeezUP API
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CostSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CostSettingsTests
    {
        // TODO uncomment below to declare an instance variable for CostSettings
        //private CostSettings instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CostSettings
            //instance = new CostSettings();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CostSettings
        /// </summary>
        [Test]
        public void CostSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CostSettings
            //Assert.IsInstanceOfType<CostSettings> (instance, "variable 'instance' is a CostSettings");
        }

        /// <summary>
        /// Test the property 'CostType'
        /// </summary>
        [Test]
        public void CostTypeTest()
        {
            // TODO unit test for the property 'CostType'
        }
        /// <summary>
        /// Test the property 'GlobalCostValue'
        /// </summary>
        [Test]
        public void GlobalCostValueTest()
        {
            // TODO unit test for the property 'GlobalCostValue'
        }

    }

}
