/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing LinksGetContractsLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class LinksGetContractsLinkTests
    {
        // TODO uncomment below to declare an instance variable for LinksGetContractsLink
        //private LinksGetContractsLink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of LinksGetContractsLink
            //instance = new LinksGetContractsLink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of LinksGetContractsLink
        /// </summary>
        [Test]
        public void LinksGetContractsLinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LinksGetContractsLink
            //Assert.IsInstanceOfType<LinksGetContractsLink> (instance, "variable 'instance' is a LinksGetContractsLink");
        }

        /// <summary>
        /// Test the property 'DocUrl'
        /// </summary>
        [Test]
        public void DocUrlTest()
        {
            // TODO unit test for the property 'DocUrl'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'OperationId'
        /// </summary>
        [Test]
        public void OperationIdTest()
        {
            // TODO unit test for the property 'OperationId'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Templated'
        /// </summary>
        [Test]
        public void TemplatedTest()
        {
            // TODO unit test for the property 'Templated'
        }
        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Test]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

    }

}
