/* 
 * Public - Security
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketplaceOrderStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketplaceOrderStatusTests
    {
        // TODO uncomment below to declare an instance variable for MarketplaceOrderStatus
        //private MarketplaceOrderStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketplaceOrderStatus
            //instance = new MarketplaceOrderStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketplaceOrderStatus
        /// </summary>
        [Test]
        public void MarketplaceOrderStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketplaceOrderStatus
            //Assert.IsInstanceOfType<MarketplaceOrderStatus> (instance, "variable 'instance' is a MarketplaceOrderStatus");
        }


    }

}
