/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing OrderListLight
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OrderListLightTests
    {
        // TODO uncomment below to declare an instance variable for OrderListLight
        //private OrderListLight instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of OrderListLight
            //instance = new OrderListLight();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of OrderListLight
        /// </summary>
        [Test]
        public void OrderListLightInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OrderListLight
            //Assert.IsInstanceOfType<OrderListLight> (instance, "variable 'instance' is a OrderListLight");
        }

        /// <summary>
        /// Test the property 'PaginationResult'
        /// </summary>
        [Test]
        public void PaginationResultTest()
        {
            // TODO unit test for the property 'PaginationResult'
        }
        /// <summary>
        /// Test the property 'Orders'
        /// </summary>
        [Test]
        public void OrdersTest()
        {
            // TODO unit test for the property 'Orders'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
