/* 
 * BeezUP API
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing RuleExecutionReportingLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class RuleExecutionReportingLinksTests
    {
        // TODO uncomment below to declare an instance variable for RuleExecutionReportingLinks
        //private RuleExecutionReportingLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of RuleExecutionReportingLinks
            //instance = new RuleExecutionReportingLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of RuleExecutionReportingLinks
        /// </summary>
        [Test]
        public void RuleExecutionReportingLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" RuleExecutionReportingLinks
            //Assert.IsInstanceOfType<RuleExecutionReportingLinks> (instance, "variable 'instance' is a RuleExecutionReportingLinks");
        }

        /// <summary>
        /// Test the property 'Rule'
        /// </summary>
        [Test]
        public void RuleTest()
        {
            // TODO unit test for the property 'Rule'
        }

    }

}
