/* 
 * Public - Security
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing StoreHeader
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StoreHeaderTests
    {
        // TODO uncomment below to declare an instance variable for StoreHeader
        //private StoreHeader instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StoreHeader
            //instance = new StoreHeader();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StoreHeader
        /// </summary>
        [Test]
        public void StoreHeaderInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StoreHeader
            //Assert.IsInstanceOfType<StoreHeader> (instance, "variable 'instance' is a StoreHeader");
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Test]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
        /// <summary>
        /// Test the property 'CountryIsoCodeAlpha3'
        /// </summary>
        [Test]
        public void CountryIsoCodeAlpha3Test()
        {
            // TODO unit test for the property 'CountryIsoCodeAlpha3'
        }
        /// <summary>
        /// Test the property 'Sectors'
        /// </summary>
        [Test]
        public void SectorsTest()
        {
            // TODO unit test for the property 'Sectors'
        }
        /// <summary>
        /// Test the property 'StoreId'
        /// </summary>
        [Test]
        public void StoreIdTest()
        {
            // TODO unit test for the property 'StoreId'
        }
        /// <summary>
        /// Test the property 'UserRole'
        /// </summary>
        [Test]
        public void UserRoleTest()
        {
            // TODO unit test for the property 'UserRole'
        }
        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'OwnerUserId'
        /// </summary>
        [Test]
        public void OwnerUserIdTest()
        {
            // TODO unit test for the property 'OwnerUserId'
        }
        /// <summary>
        /// Test the property 'ShareCount'
        /// </summary>
        [Test]
        public void ShareCountTest()
        {
            // TODO unit test for the property 'ShareCount'
        }
        /// <summary>
        /// Test the property 'CreationUtcDate'
        /// </summary>
        [Test]
        public void CreationUtcDateTest()
        {
            // TODO unit test for the property 'CreationUtcDate'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
