/* 
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing FunctionalityRightInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FunctionalityRightInfoTests
    {
        // TODO uncomment below to declare an instance variable for FunctionalityRightInfo
        //private FunctionalityRightInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FunctionalityRightInfo
            //instance = new FunctionalityRightInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FunctionalityRightInfo
        /// </summary>
        [Test]
        public void FunctionalityRightInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FunctionalityRightInfo
            //Assert.IsInstanceOfType<FunctionalityRightInfo> (instance, "variable 'instance' is a FunctionalityRightInfo");
        }

        /// <summary>
        /// Test the property 'FunctionalityCode'
        /// </summary>
        [Test]
        public void FunctionalityCodeTest()
        {
            // TODO unit test for the property 'FunctionalityCode'
        }
        /// <summary>
        /// Test the property 'MaxValueInterger'
        /// </summary>
        [Test]
        public void MaxValueIntergerTest()
        {
            // TODO unit test for the property 'MaxValueInterger'
        }
        /// <summary>
        /// Test the property 'Unlimited'
        /// </summary>
        [Test]
        public void UnlimitedTest()
        {
            // TODO unit test for the property 'Unlimited'
        }

    }

}
