/* 
 * Marketplaces - Orders
 *
 * The features exposed in this API are centered around managing Orders harvested from your configured marketplaces.\\ This includes: - fetching current information (as known by BeezUP) for a single or multiple Orders, - requesting Order harvest to synchronize your marketplaces and BeezUP accounts, - changing BeezUP data and requesting changes to your marketplaces (accepting, shipping, etc), - configuring automatic changes to marketplace based our newly fetched data, - creating and exporting reports for your Orders. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace IO.Swagger.Model
{
    /// <summary>
    /// AccountSynchronizations
    /// </summary>
    [DataContract]
    public partial class AccountSynchronizations :  IEquatable<AccountSynchronizations>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AccountSynchronizations" /> class.
        /// </summary>
        /// <param name="_AccountSynchronizations">_AccountSynchronizations.</param>
        public AccountSynchronizations(List<AccountSynchronization> _AccountSynchronizations = default(List<AccountSynchronization>))
        {
            this._AccountSynchronizations = _AccountSynchronizations;
        }
        
        /// <summary>
        /// Gets or Sets _AccountSynchronizations
        /// </summary>
        [DataMember(Name="accountSynchronizations", EmitDefaultValue=false)]
        public List<AccountSynchronization> _AccountSynchronizations { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AccountSynchronizations {\n");
            sb.Append("  _AccountSynchronizations: ").Append(_AccountSynchronizations).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AccountSynchronizations);
        }

        /// <summary>
        /// Returns true if AccountSynchronizations instances are equal
        /// </summary>
        /// <param name="other">Instance of AccountSynchronizations to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AccountSynchronizations other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this._AccountSynchronizations == other._AccountSynchronizations ||
                    this._AccountSynchronizations != null &&
                    this._AccountSynchronizations.SequenceEqual(other._AccountSynchronizations)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this._AccountSynchronizations != null)
                    hash = hash * 59 + this._AccountSynchronizations.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
