/* 
 * Analytics
 *
 * This API will help you to manage the tracking of your clicks and your sales, get reporting on this trackings and put in place rules based on this reporting to automatically optimize your channel catalogs. \\ Also, you will be able to consult the rule execution reporting. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportFiltersTests
    {
        // TODO uncomment below to declare an instance variable for ReportFilters
        //private ReportFilters instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportFilters
            //instance = new ReportFilters();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportFilters
        /// </summary>
        [Test]
        public void ReportFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportFilters
            //Assert.IsInstanceOfType<ReportFilters> (instance, "variable 'instance' is a ReportFilters");
        }

        /// <summary>
        /// Test the property '_ReportFilters'
        /// </summary>
        [Test]
        public void _ReportFiltersTest()
        {
            // TODO unit test for the property '_ReportFilters'
        }
        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Test]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

    }

}
