/* 
 * Channels
 *
 * This api allows you to get access to your channels
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeezUPCommonLink2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeezUPCommonLink2Tests
    {
        // TODO uncomment below to declare an instance variable for BeezUPCommonLink2
        //private BeezUPCommonLink2 instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeezUPCommonLink2
            //instance = new BeezUPCommonLink2();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeezUPCommonLink2
        /// </summary>
        [Test]
        public void BeezUPCommonLink2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeezUPCommonLink2
            //Assert.IsInstanceOfType<BeezUPCommonLink2> (instance, "variable 'instance' is a BeezUPCommonLink2");
        }

        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Test]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'OperationId'
        /// </summary>
        [Test]
        public void OperationIdTest()
        {
            // TODO unit test for the property 'OperationId'
        }
        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Test]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }
        /// <summary>
        /// Test the property 'Parameters'
        /// </summary>
        [Test]
        public void ParametersTest()
        {
            // TODO unit test for the property 'Parameters'
        }
        /// <summary>
        /// Test the property 'Info'
        /// </summary>
        [Test]
        public void InfoTest()
        {
            // TODO unit test for the property 'Info'
        }

    }

}
