/* 
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing CreditCardInfoResponseLinks
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class CreditCardInfoResponseLinksTests
    {
        // TODO uncomment below to declare an instance variable for CreditCardInfoResponseLinks
        //private CreditCardInfoResponseLinks instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of CreditCardInfoResponseLinks
            //instance = new CreditCardInfoResponseLinks();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of CreditCardInfoResponseLinks
        /// </summary>
        [Test]
        public void CreditCardInfoResponseLinksInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditCardInfoResponseLinks
            //Assert.IsInstanceOfType<CreditCardInfoResponseLinks> (instance, "variable 'instance' is a CreditCardInfoResponseLinks");
        }

        /// <summary>
        /// Test the property 'Self'
        /// </summary>
        [Test]
        public void SelfTest()
        {
            // TODO unit test for the property 'Self'
        }
        /// <summary>
        /// Test the property 'SaveCreditCardInfo'
        /// </summary>
        [Test]
        public void SaveCreditCardInfoTest()
        {
            // TODO unit test for the property 'SaveCreditCardInfo'
        }

    }

}
