/* 
 * Analytics
 *
 * This API will help you to manage the tracking of your clicks and your sales, get reporting on this trackings and put in place rules based on this reporting to automatically optimize your channel catalogs. \\ Also, you will be able to consult the rule execution reporting. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ReportIndicatorFilter
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReportIndicatorFilterTests
    {
        // TODO uncomment below to declare an instance variable for ReportIndicatorFilter
        //private ReportIndicatorFilter instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReportIndicatorFilter
            //instance = new ReportIndicatorFilter();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReportIndicatorFilter
        /// </summary>
        [Test]
        public void ReportIndicatorFilterInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReportIndicatorFilter
            //Assert.IsInstanceOfType<ReportIndicatorFilter> (instance, "variable 'instance' is a ReportIndicatorFilter");
        }

        /// <summary>
        /// Test the property 'Indicator'
        /// </summary>
        [Test]
        public void IndicatorTest()
        {
            // TODO unit test for the property 'Indicator'
        }
        /// <summary>
        /// Test the property 'OperatorName'
        /// </summary>
        [Test]
        public void OperatorNameTest()
        {
            // TODO unit test for the property 'OperatorName'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

    }

}
