/* 
 * BeezUP API
 *
 * This API will allow you to create your account and to get your tokens. \\ If you lost your password, you have an operation to get it back. 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;

namespace IO.Swagger.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IChannelsChannelsGlobalApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// List all available channel for this store
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>List&lt;ChannelHeader&gt;</returns>
        List<ChannelHeader> GetAvailableChannels (string storeId);

        /// <summary>
        /// List all available channel for this store
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>ApiResponse of List&lt;ChannelHeader&gt;</returns>
        ApiResponse<List<ChannelHeader>> GetAvailableChannelsWithHttpInfo (string storeId);
        /// <summary>
        /// Get channel categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>ChannelRootCategory</returns>
        ChannelRootCategory GetChannelCategories (string channelId, List<string> acceptEncoding);

        /// <summary>
        /// Get channel categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>ApiResponse of ChannelRootCategory</returns>
        ApiResponse<ChannelRootCategory> GetChannelCategoriesWithHttpInfo (string channelId, List<string> acceptEncoding);
        /// <summary>
        /// Get channel columns
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>List&lt;ChannelColumn&gt;</returns>
        List<ChannelColumn> GetChannelColumns (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null);

        /// <summary>
        /// Get channel columns
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>ApiResponse of List&lt;ChannelColumn&gt;</returns>
        ApiResponse<List<ChannelColumn>> GetChannelColumnsWithHttpInfo (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null);
        /// <summary>
        /// Get channel information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>ChannelInfo</returns>
        ChannelInfo GetChannelInfo (string channelId);

        /// <summary>
        /// Get channel information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>ApiResponse of ChannelInfo</returns>
        ApiResponse<ChannelInfo> GetChannelInfoWithHttpInfo (string channelId);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// List all available channel for this store
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>Task of List&lt;ChannelHeader&gt;</returns>
        System.Threading.Tasks.Task<List<ChannelHeader>> GetAvailableChannelsAsync (string storeId);

        /// <summary>
        /// List all available channel for this store
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>Task of ApiResponse (List&lt;ChannelHeader&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ChannelHeader>>> GetAvailableChannelsAsyncWithHttpInfo (string storeId);
        /// <summary>
        /// Get channel categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>Task of ChannelRootCategory</returns>
        System.Threading.Tasks.Task<ChannelRootCategory> GetChannelCategoriesAsync (string channelId, List<string> acceptEncoding);

        /// <summary>
        /// Get channel categories
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>Task of ApiResponse (ChannelRootCategory)</returns>
        System.Threading.Tasks.Task<ApiResponse<ChannelRootCategory>> GetChannelCategoriesAsyncWithHttpInfo (string channelId, List<string> acceptEncoding);
        /// <summary>
        /// Get channel columns
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>Task of List&lt;ChannelColumn&gt;</returns>
        System.Threading.Tasks.Task<List<ChannelColumn>> GetChannelColumnsAsync (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null);

        /// <summary>
        /// Get channel columns
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ChannelColumn&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<ChannelColumn>>> GetChannelColumnsAsyncWithHttpInfo (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null);
        /// <summary>
        /// Get channel information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>Task of ChannelInfo</returns>
        System.Threading.Tasks.Task<ChannelInfo> GetChannelInfoAsync (string channelId);

        /// <summary>
        /// Get channel information
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>Task of ApiResponse (ChannelInfo)</returns>
        System.Threading.Tasks.Task<ApiResponse<ChannelInfo>> GetChannelInfoAsyncWithHttpInfo (string channelId);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ChannelsChannelsGlobalApi : IChannelsChannelsGlobalApi
    {
        private IO.Swagger.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelsChannelsGlobalApi"/> class.
        /// </summary>
        /// <returns></returns>
        public ChannelsChannelsGlobalApi(String basePath)
        {
            this.Configuration = new Configuration(new ApiClient(basePath));

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChannelsChannelsGlobalApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public ChannelsChannelsGlobalApi(Configuration configuration = null)
        {
            if (configuration == null) // use the default one in Configuration
                this.Configuration = Configuration.Default;
            else
                this.Configuration = configuration;

            ExceptionFactory = IO.Swagger.Client.Configuration.DefaultExceptionFactory;

            // ensure API client has configuration ready
            if (Configuration.ApiClient.Configuration == null)
            {
                this.Configuration.ApiClient.Configuration = this.Configuration;
            }
        }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(String basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public IO.Swagger.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public Dictionary<String, String> DefaultHeader()
        {
            return this.Configuration.DefaultHeader;
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            this.Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// List all available channel for this store 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>List&lt;ChannelHeader&gt;</returns>
        public List<ChannelHeader> GetAvailableChannels (string storeId)
        {
             ApiResponse<List<ChannelHeader>> localVarResponse = GetAvailableChannelsWithHttpInfo(storeId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// List all available channel for this store 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>ApiResponse of List&lt;ChannelHeader&gt;</returns>
        public ApiResponse< List<ChannelHeader> > GetAvailableChannelsWithHttpInfo (string storeId)
        {
            // verify the required parameter 'storeId' is set
            if (storeId == null)
                throw new ApiException(400, "Missing required parameter 'storeId' when calling ChannelsChannelsGlobalApi->GetAvailableChannels");

            var localVarPath = "/user/channels/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (storeId != null) localVarQueryParams.Add("storeId", Configuration.ApiClient.ParameterToString(storeId)); // query parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAvailableChannels", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ChannelHeader>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ChannelHeader>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ChannelHeader>)));
            
        }

        /// <summary>
        /// List all available channel for this store 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>Task of List&lt;ChannelHeader&gt;</returns>
        public async System.Threading.Tasks.Task<List<ChannelHeader>> GetAvailableChannelsAsync (string storeId)
        {
             ApiResponse<List<ChannelHeader>> localVarResponse = await GetAvailableChannelsAsyncWithHttpInfo(storeId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// List all available channel for this store 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="storeId">The store identifier</param>
        /// <returns>Task of ApiResponse (List&lt;ChannelHeader&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ChannelHeader>>> GetAvailableChannelsAsyncWithHttpInfo (string storeId)
        {
            // verify the required parameter 'storeId' is set
            if (storeId == null)
                throw new ApiException(400, "Missing required parameter 'storeId' when calling ChannelsChannelsGlobalApi->GetAvailableChannels");

            var localVarPath = "/user/channels/";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (storeId != null) localVarQueryParams.Add("storeId", Configuration.ApiClient.ParameterToString(storeId)); // query parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetAvailableChannels", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ChannelHeader>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ChannelHeader>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ChannelHeader>)));
            
        }

        /// <summary>
        /// Get channel categories 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>ChannelRootCategory</returns>
        public ChannelRootCategory GetChannelCategories (string channelId, List<string> acceptEncoding)
        {
             ApiResponse<ChannelRootCategory> localVarResponse = GetChannelCategoriesWithHttpInfo(channelId, acceptEncoding);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get channel categories 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>ApiResponse of ChannelRootCategory</returns>
        public ApiResponse< ChannelRootCategory > GetChannelCategoriesWithHttpInfo (string channelId, List<string> acceptEncoding)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelCategories");
            // verify the required parameter 'acceptEncoding' is set
            if (acceptEncoding == null)
                throw new ApiException(400, "Missing required parameter 'acceptEncoding' when calling ChannelsChannelsGlobalApi->GetChannelCategories");

            var localVarPath = "/user/channels/{channelId}/categories";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter
            if (acceptEncoding != null) localVarHeaderParams.Add("Accept-Encoding", Configuration.ApiClient.ParameterToString(acceptEncoding)); // header parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelCategories", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ChannelRootCategory>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ChannelRootCategory) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ChannelRootCategory)));
            
        }

        /// <summary>
        /// Get channel categories 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>Task of ChannelRootCategory</returns>
        public async System.Threading.Tasks.Task<ChannelRootCategory> GetChannelCategoriesAsync (string channelId, List<string> acceptEncoding)
        {
             ApiResponse<ChannelRootCategory> localVarResponse = await GetChannelCategoriesAsyncWithHttpInfo(channelId, acceptEncoding);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get channel categories 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <returns>Task of ApiResponse (ChannelRootCategory)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ChannelRootCategory>> GetChannelCategoriesAsyncWithHttpInfo (string channelId, List<string> acceptEncoding)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelCategories");
            // verify the required parameter 'acceptEncoding' is set
            if (acceptEncoding == null)
                throw new ApiException(400, "Missing required parameter 'acceptEncoding' when calling ChannelsChannelsGlobalApi->GetChannelCategories");

            var localVarPath = "/user/channels/{channelId}/categories";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter
            if (acceptEncoding != null) localVarHeaderParams.Add("Accept-Encoding", Configuration.ApiClient.ParameterToString(acceptEncoding)); // header parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelCategories", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ChannelRootCategory>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ChannelRootCategory) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ChannelRootCategory)));
            
        }

        /// <summary>
        /// Get channel columns 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>List&lt;ChannelColumn&gt;</returns>
        public List<ChannelColumn> GetChannelColumns (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null)
        {
             ApiResponse<List<ChannelColumn>> localVarResponse = GetChannelColumnsWithHttpInfo(channelId, acceptEncoding, request);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get channel columns 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>ApiResponse of List&lt;ChannelColumn&gt;</returns>
        public ApiResponse< List<ChannelColumn> > GetChannelColumnsWithHttpInfo (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelColumns");
            // verify the required parameter 'acceptEncoding' is set
            if (acceptEncoding == null)
                throw new ApiException(400, "Missing required parameter 'acceptEncoding' when calling ChannelsChannelsGlobalApi->GetChannelColumns");

            var localVarPath = "/user/channels/{channelId}/columns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter
            if (acceptEncoding != null) localVarHeaderParams.Add("Accept-Encoding", Configuration.ApiClient.ParameterToString(acceptEncoding)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelColumns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ChannelColumn>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ChannelColumn>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ChannelColumn>)));
            
        }

        /// <summary>
        /// Get channel columns 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>Task of List&lt;ChannelColumn&gt;</returns>
        public async System.Threading.Tasks.Task<List<ChannelColumn>> GetChannelColumnsAsync (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null)
        {
             ApiResponse<List<ChannelColumn>> localVarResponse = await GetChannelColumnsAsyncWithHttpInfo(channelId, acceptEncoding, request);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get channel columns 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <param name="acceptEncoding">Indicates that the client accepts that the response will be compressed to reduce traffic size.</param>
        /// <param name="request">Allow you to filter the channel column identifier list your want to get (optional)</param>
        /// <returns>Task of ApiResponse (List&lt;ChannelColumn&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<ChannelColumn>>> GetChannelColumnsAsyncWithHttpInfo (string channelId, List<string> acceptEncoding, List<BeezUPCommonChannelColumnId> request = null)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelColumns");
            // verify the required parameter 'acceptEncoding' is set
            if (acceptEncoding == null)
                throw new ApiException(400, "Missing required parameter 'acceptEncoding' when calling ChannelsChannelsGlobalApi->GetChannelColumns");

            var localVarPath = "/user/channels/{channelId}/columns";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter
            if (acceptEncoding != null) localVarHeaderParams.Add("Accept-Encoding", Configuration.ApiClient.ParameterToString(acceptEncoding)); // header parameter
            if (request != null && request.GetType() != typeof(byte[]))
            {
                localVarPostBody = Configuration.ApiClient.Serialize(request); // http body (model) parameter
            }
            else
            {
                localVarPostBody = request; // byte array
            }

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.POST, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelColumns", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<ChannelColumn>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<ChannelColumn>) Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<ChannelColumn>)));
            
        }

        /// <summary>
        /// Get channel information 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>ChannelInfo</returns>
        public ChannelInfo GetChannelInfo (string channelId)
        {
             ApiResponse<ChannelInfo> localVarResponse = GetChannelInfoWithHttpInfo(channelId);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Get channel information 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>ApiResponse of ChannelInfo</returns>
        public ApiResponse< ChannelInfo > GetChannelInfoWithHttpInfo (string channelId)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelInfo");

            var localVarPath = "/user/channels/{channelId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ChannelInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ChannelInfo) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ChannelInfo)));
            
        }

        /// <summary>
        /// Get channel information 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>Task of ChannelInfo</returns>
        public async System.Threading.Tasks.Task<ChannelInfo> GetChannelInfoAsync (string channelId)
        {
             ApiResponse<ChannelInfo> localVarResponse = await GetChannelInfoAsyncWithHttpInfo(channelId);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Get channel information 
        /// </summary>
        /// <exception cref="IO.Swagger.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="channelId">The channel identifier</param>
        /// <returns>Task of ApiResponse (ChannelInfo)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<ChannelInfo>> GetChannelInfoAsyncWithHttpInfo (string channelId)
        {
            // verify the required parameter 'channelId' is set
            if (channelId == null)
                throw new ApiException(400, "Missing required parameter 'channelId' when calling ChannelsChannelsGlobalApi->GetChannelInfo");

            var localVarPath = "/user/channels/{channelId}";
            var localVarPathParams = new Dictionary<String, String>();
            var localVarQueryParams = new Dictionary<String, String>();
            var localVarHeaderParams = new Dictionary<String, String>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<String, String>();
            var localVarFileParams = new Dictionary<String, FileParameter>();
            Object localVarPostBody = null;

            // to determine the Content-Type header
            String[] localVarHttpContentTypes = new String[] {
                "application/json"
            };
            String localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            String[] localVarHttpHeaderAccepts = new String[] {
                "application/json"
            };
            String localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            // set "format" to json by default
            // e.g. /pet/{petId}.{format} becomes /pet/{petId}.json
            localVarPathParams.Add("format", "json");
            if (channelId != null) localVarPathParams.Add("channelId", Configuration.ApiClient.ParameterToString(channelId)); // path parameter

            // authentication (api_key) required
            if (!String.IsNullOrEmpty(Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key")))
            {
                localVarHeaderParams["Ocp-Apim-Subscription-Key"] = Configuration.GetApiKeyWithPrefix("Ocp-Apim-Subscription-Key");
            }

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse) await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int) localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("GetChannelInfo", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<ChannelInfo>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (ChannelInfo) Configuration.ApiClient.Deserialize(localVarResponse, typeof(ChannelInfo)));
            
        }

    }
}
