/* 
 * Public - Channels
 *
 * This api allows you to get access to the channels. The main use case is our public commercial web site.
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing BeezUPCommonUserErrorMessage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class BeezUPCommonUserErrorMessageTests
    {
        // TODO uncomment below to declare an instance variable for BeezUPCommonUserErrorMessage
        //private BeezUPCommonUserErrorMessage instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of BeezUPCommonUserErrorMessage
            //instance = new BeezUPCommonUserErrorMessage();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of BeezUPCommonUserErrorMessage
        /// </summary>
        [Test]
        public void BeezUPCommonUserErrorMessageInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" BeezUPCommonUserErrorMessage
            //Assert.IsInstanceOfType<BeezUPCommonUserErrorMessage> (instance, "variable 'instance' is a BeezUPCommonUserErrorMessage");
        }

        /// <summary>
        /// Test the property 'DocUrl'
        /// </summary>
        [Test]
        public void DocUrlTest()
        {
            // TODO unit test for the property 'DocUrl'
        }
        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Test]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'CultureName'
        /// </summary>
        [Test]
        public void CultureNameTest()
        {
            // TODO unit test for the property 'CultureName'
        }
        /// <summary>
        /// Test the property 'Arguments'
        /// </summary>
        [Test]
        public void ArgumentsTest()
        {
            // TODO unit test for the property 'Arguments'
        }

    }

}
