/* 
 * BeezUP API
 *
 * This is the RESTful API of BeezUP which allows you to manage everything related to BeezUP
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing MarketplaceTechnicalCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MarketplaceTechnicalCodeTests
    {
        // TODO uncomment below to declare an instance variable for MarketplaceTechnicalCode
        //private MarketplaceTechnicalCode instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MarketplaceTechnicalCode
            //instance = new MarketplaceTechnicalCode();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MarketplaceTechnicalCode
        /// </summary>
        [Test]
        public void MarketplaceTechnicalCodeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MarketplaceTechnicalCode
            //Assert.IsInstanceOfType<MarketplaceTechnicalCode> (instance, "variable 'instance' is a MarketplaceTechnicalCode");
        }


    }

}
