/* 
 * Customer
 *
 * This API will gives you the ability to : - manage your account - manage your stores - shares your stores with your friends - manage your contracts - access to your invoices 
 *
 * OpenAPI spec version: 2.0
 * Contact: support@beezup.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;
using IO.Swagger.Model;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AccountApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class AccountApiTests
    {
        private AccountApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new AccountApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AccountApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' AccountApi
            //Assert.IsInstanceOfType(typeof(AccountApi), instance, "instance is a AccountApi");
        }

        
        /// <summary>
        /// Test ActivateUserAccount
        /// </summary>
        [Test]
        public void ActivateUserAccountTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string emailActivationId = null;
            //instance.ActivateUserAccount(emailActivationId);
            
        }
        
        /// <summary>
        /// Test ChangePassword
        /// </summary>
        [Test]
        public void ChangePasswordTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ChangePasswordRequest request = null;
            //instance.ChangePassword(request);
            
        }
        
        /// <summary>
        /// Test GetCreditCardInfo
        /// </summary>
        [Test]
        public void GetCreditCardInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetCreditCardInfo();
            //Assert.IsInstanceOf<CreditCardInfoResponse> (response, "response is CreditCardInfoResponse");
        }
        
        /// <summary>
        /// Test GetProfilePictureInfo
        /// </summary>
        [Test]
        public void GetProfilePictureInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetProfilePictureInfo();
            //Assert.IsInstanceOf<ProfilePictureInfoResponse> (response, "response is ProfilePictureInfoResponse");
        }
        
        /// <summary>
        /// Test GetUserAccountInfo
        /// </summary>
        [Test]
        public void GetUserAccountInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetUserAccountInfo();
            //Assert.IsInstanceOf<AccountInfo> (response, "response is AccountInfo");
        }
        
        /// <summary>
        /// Test ResendEmailActivation
        /// </summary>
        [Test]
        public void ResendEmailActivationTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //instance.ResendEmailActivation();
            
        }
        
        /// <summary>
        /// Test SaveCompanyInfo
        /// </summary>
        [Test]
        public void SaveCompanyInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CompanyInfo request = null;
            //instance.SaveCompanyInfo(request);
            
        }
        
        /// <summary>
        /// Test SaveCreditCardInfo
        /// </summary>
        [Test]
        public void SaveCreditCardInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreditCardInfo request = null;
            //instance.SaveCreditCardInfo(request);
            
        }
        
        /// <summary>
        /// Test SavePersonalInfo
        /// </summary>
        [Test]
        public void SavePersonalInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //PersonalInfo request = null;
            //instance.SavePersonalInfo(request);
            
        }
        
        /// <summary>
        /// Test SaveProfilePictureInfo
        /// </summary>
        [Test]
        public void SaveProfilePictureInfoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //ProfilePictureInfo request = null;
            //instance.SaveProfilePictureInfo(request);
            
        }
        
    }

}
